### ISSUE TITLE
Links!

### ISSUE THREAD

**Issue by TrickJoker312** [GameHub88/GameHub#1]
Are there any more links for this site? If so, please link them below. I'd really appreciate it!

**Comment by Russell2259** [comment]
Sorry, unfortunately the base servers running the GameHub API are down and are being worked on, so none of the instances work. We are currently working on the issue. 

In the meantime you can use one of the buttons in the readme to fork and run the service, though it may not work until the servers are fixed.

Thanks for your patience!
